name: Variable in develop
on: 
  push:
    branches:
      - develop
env:
  MY_VARIABLE: ${{ env.MY_VARIABLE }}
jobs:
  print-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variable
        run: echo "The value of the env variable is:" $MY_VARIABLE
  deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.MY_VARIABLE == 'abc'}}
    steps:
      - name: Deploy Application
        run: echo "Deploying application... MY_VARIABLE is matched!"  

