name: Variable in develop
on: 
  push:
    branches:
      - develop

jobs:
  print-variable:
    env:
      MY_VARIABLE: ${{ secrets.MY_VARIABLE }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Variable
        run: echo "The value of the variable is:" $MY_VARIABLE

